### PR TITLE
Use correct docker image name

### LINKED ISSUE #81: README usage instruction is pointing to incorrect server image name
Currently, all the usage instructions are pointing to the incorrect image name `gocd/docker-gocd-server:v19.4.0`. 

Screenshot 2019-05-28 at 12 05 12

It should be pointing to `gocd/gocd-server:v19.4.0`

### PR DESCRIPTION
**Pull request by arvindsv**
Fixes #81.

/cc @ankitsri11

### CODE REVIEW

**Comment by arvindsv** [comment]
@kritika-singh3 @GaneshSPatil Can one of you look at this? I had to update the details in https://hub.docker.com/r/gocd/gocd-server once more this release (today). Not sure if this is the source of truth for it.

**Comment by varshavaradarajan** [comment]
https://github.com/gocd/gocd/blob/master/buildSrc/src/main/resources/gocd-docker-server/README.md.ftl#L10 - change $imageName to gocd-server - there's no need for a variable for it. $imageName == github repo name which causes this problem. Not sure if agents have the same problem. 

The dockerhub desc is updated from this updated README at release time only - https://github.com/gocd/codesigning/blob/master/lib/update_dockerhub_full_description.js

**Comment by ketan** [comment]
Maybe introduce another attribute repoName on the interface?

**Comment by kritika-singh3** [comment]
> https://github.com/gocd/gocd/blob/master/buildSrc/src/main/resources/gocd-docker-server/README.md.ftl#L10 - change $imageName to gocd-server - there's no need for a variable for it. $imageName == github repo name which causes this problem. Not sure if agents have the same problem.

Can't do that as we publish 2 gocd-server images (alpine based and centos-7 based). But will fix the error of `imageName == github repo name`. That shouldn't be the case. Thanks for pointing it out.

**Pull request closed without merging**
