### PR TITLE
update Dockerfile

### PR DESCRIPTION
**Pull request by anmolnagpal**

### CODE REVIEW

**Comment by ghost** [comment]
[CLA assistant check](https://cla.gocd.org/gocd/docker-gocd-server?pullRequest=30) <br/>All committers have signed the CLA.

**Comment by ketan** [comment]
What's the motivation of this PR? The file is automatically generated from a template `Dockerfile.erb`, so perhaps you want to update that instead.

**Comment by anmolnagpal** [comment]
@ketan 

Incase any of the one want to test with different version he/she have to change the same  more then 1 place but if we use this way it will be easy.

**Comment by ketan** [comment]
Perhaps you want to see this https://github.com/gocd/docker-gocd-server#12-build-one-locally and see how you may improve this.

**Pull request closed without merging**
